Compile in the following order:
telepathy-qt4
nepomuk
main
accounts-kcm
accounts-kcm-plugins
approver
callui
chathandler
contactlist
contacts-applet
filehandler
launcher-kded
sendfile
presence-applet
presence-dataengine 
