#!/bin/sh

[ -f ~/.mcwrapperrc ] && . ~/.mcwrapperrc || (
echo "# Home directory for Minecraft
# You can override it any time by specifying MC=/path/to/dir
home_directory=~
# Heap size
heap_max=1024M
heap_min=256M
# LWJGL version to use w/Java7
lwjgl_version=2.8.1
# Enable/disable optimus. You can put 'ask' here to ask every time.
use_optimus=ask
# Put the full texture pack filename, 'keep' or 'default' here.
optimus_texture=\"default\"
intel_texture=\"default\"" > ~/.mcwrapperrc
)

[ -z "$home_directory" ]  && home_directory=~
[ -z "$heap_max" ]        && heap_max=1024M
[ -z "$heap_min" ]        && heap_min=256M
[ -z "$lwjgl_version" ]   && lwjgl_version=2.8.1
[ -z "$use_optimus" ]     && use_optimus=ask_auto
[ -z "$optimus_texture" ] && optimus_texture="keep"
[ -z "$intel_texture" ]   && intel_texture="keep"

! [ -z "$MC" ] && home_directory=$MC

ABSOLUTE=$(cd $home_directory; pwd)
LWJGL=$lwjgl_version

wget_gui() {
	eval wget -N --progress=bar:force --no-check-certificate $1 2>&1 | zenity --title="MCWrapper" \
		--progress --auto-close --auto-kill --width=400 --no-cancel --text="$2"
}

set_texture() {
	cd $ABSOLUTE/.minecraft/
	if [ -f options.txt ]; then
		if [ "$1" == "keep" ]; then
			return
		else
			sed "s/skin:.*//g" -i options.txt
			if [ "$1" != "default" ]; then
				echo "skin:$1" >> options.txt
			fi
		fi
	fi
}

# Make the home directory
mkdir -p $ABSOLUTE/.minecraft/bin
# Download the launcher
cd $ABSOLUTE/.minecraft/
wget_gui https://s3.amazonaws.com/MinecraftDownload/launcher/minecraft.jar "Checking for updates..."
cd $ABSOLUTE/.minecraft/bin

# Check for java7
if which java7-java &> /dev/null; then
	JAVA=java7-java
	JAVAP=java7-javap
else
	JAVA=java
	JAVAP=javap
fi

# JDK7 doesn't work with LWJGL < 2.8.1, so we check it
if [ -f minecraft.jar ]; then
	# If we have LWJGL and Java 7...
	if $JAVA -version 2>&1 | grep -q 1.7; then
		if [ -f lwjgl.jar ]; then
			# Check LWJGL version (HAXZ!!!)
			unzip -o lwjgl.jar org/lwjgl/Sys.class > /dev/null
			if $JAVAP -p -constants -cp . org.lwjgl.Sys | grep -q $LWJGL; then
				lwjgl_ok=1
			else
				lwjgl_ok=0
			fi
			rm -rf org
		else
			# No LWJGL at all, so let's download latest :)
			lwjgl_ok=0
		fi
      else
	      # We're fine as it is
	      lwjgl_ok=1
      fi
else
	# The launcher will redownload anyway if there's no mc.jar
	lwjgl_ok=1
	# So let's notify people :)
	if $JAVA -version 2>&1 | grep -q 1.7; then 
		zenity --warning --text="We'll need to update LWJGL to 2.8.1 for OpenJDK7, so you will probably get a black window of death the first time you start Minecraft. Restart the game to make it work."
	fi
fi

if [ "$lwjgl_ok" != "1" ]; then
	# Download/install new LWJGL
	wget_gui "http://citylan.dl.sourceforge.net/project/java-game-lib/Official%20Releases/LWJGL%20$LWJGL/lwjgl-$LWJGL.zip" "Downloading lwjgl..."
	unzip -o lwjgl-$LWJGL.zip 2>&1 | zenity --title="MCWrapper" \
					  --progress --auto-close --auto-kill --width=400 --no-cancel  --text="Extracting lwjgl..." --pulsate
	mv lwjgl-$LWJGL/jar/jinput.jar .
	mv lwjgl-$LWJGL/jar/lwjgl.jar .
	mv lwjgl-$LWJGL/jar/lwjgl_util.jar .
	mkdir -p natives
	mv lwjgl-$LWJGL/native/linux/* natives
	rm -rf lwjgl-$LWJGL{,.zip}
fi

# Check for Optimus
if which optirun &> /dev/null; then
	# We have optimus
	if glxinfo | grep -q VirtualGL; then
		# Already running on nvidia
		optirun=""
	else
		# Not running on nvidia
		if [ "$use_optimus" == "1" ]; then
			optirun="optirun "
		elif [ "$use_optimus" == "0" ]; then
			optirun=""
		else
			if zenity --question --text="Would you like to use NVidia card?"; then
				optirun="optirun "
                if [ "$use_optimus" == "ask_auto" ]; then
    				zenity --warning --text="To set up Optimus, edit ~/.mcwrapperrc."
                fi
			else
				optirun=""
			fi
		fi
	fi
fi

if [ "$optirun" == "" ]; then
	echo "Running without Optimus..."
	set_texture "$intel_texture"
else
	echo "Running with Optimus"
	set_texture "$optimus_texture"
fi

cd $ABSOLUTE/.minecraft/
echo "Running in $ABSOLUTE..."
# Start the launcher
$optirun $JAVA -Duser.home=$ABSOLUTE -Xmx${heap_max} -Xms${heap_min} -jar $ABSOLUTE/.minecraft/minecraft.jar
